--<ScriptOptions statementTerminator=";"/>

CREATE TABLE MEASURE (
		MEASURE_ID NUMBER(22 , 0) NOT NULL,
		MEASURE_NAME VARCHAR2(50),
		IS_ACTIVE NUMBER(22 , 0),
		IMPORT_OR_EXPORT CHAR(1),
		ORDER_KEY NUMBER(22 , 0)
	);

CREATE TABLE METER_POINT_TYPE (
		POINT_TYPE_ID NUMBER(1 , 0) NOT NULL,
		POINT_NAME VARCHAR2(100) NOT NULL
	);

CREATE TABLE AREA (
		AREA_CODE VARCHAR2(10) NOT NULL,
		PROVINCE_CODE VARCHAR2(10) NOT NULL,
		AREA_NAME VARCHAR2(100) NOT NULL,
		DESCRIPTION VARCHAR2(250),
		STATUS NUMBER(2 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE DEFAULT sysdate  NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE,
		LICENSE_CODE VARCHAR2(4)
	);

CREATE TABLE MEASURE_CELL (
		MODEL_ID NUMBER(22 , 0) NOT NULL,
		MEASURE_ID NUMBER(22 , 0) NOT NULL,
		CELL VARCHAR2(20),
		FILE_TYPE VARCHAR2(5),
		VALUE_CALC VARCHAR2(20)
	);

CREATE TABLE METER (
		CEB_SERIAL_NO VARCHAR2(20) NOT NULL,
		BATCH_ID VARCHAR2(20),
		CURRENT_RATING NUMBER(19 , 2),
		MODIFIED_DATE DATE,
		REMARK VARCHAR2(255),
		STATUS VARCHAR2(5),
		UPDATED_BY VARCHAR2(15),
		SERIAL_NO VARCHAR2(20),
		UPDATED_DATE DATE DEFAULT sysdate,
		CREATED_BY VARCHAR2(15),
		CREATED_DATE DATE
	);

CREATE TABLE GRID_SUBSTATION (
		GSS_ID NUMBER(22 , 0) NOT NULL,
		LICENSE_CODE VARCHAR2(4) NOT NULL,
		GSS_CODE VARCHAR2(50) NOT NULL,
		GSS_NAME VARCHAR2(150) NOT NULL,
		NOMINAL_VOLTAGE VARCHAR2(10),
		LATITUDE NUMBER(12 , 9),
		LONGITUDE NUMBER(12 , 9),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE DEFAULT SYSDATE  NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE TABLE METER_POINT (
		POINT_ID NUMBER(22 , 0) NOT NULL,
		GSS_ID NUMBER(22 , 0),
		SERIAL_NO VARCHAR2(75) NOT NULL,
		METER_POINT_NAME VARCHAR2(100) NOT NULL,
		METER_POINT_CODE VARCHAR2(50),
		DESCRIPTION VARCHAR2(250),
		NOMINAL_VOLTAGE NUMBER(22 , 0),
		RATED_VOLTAGE NUMBER(22 , 0),
		RATED_FREQUENCY NUMBER(22 , 0),
		LATITUDE NUMBER(12 , 9),
		LONGITUDE NUMBER(12 , 9),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE DEFAULT sysdate  NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE DEFAULT SYSDATE ,
		POINT_TYPE_ID NUMBER(1 , 0) NOT NULL,
		PSS_ID NUMBER(22 , 0),
		CEB_SERIAL_NO VARCHAR2(20) NOT NULL,
		LICENSE_CODE VARCHAR2(20) NOT NULL,
		AREA_CODE VARCHAR2(10),
		CEB_PROVINCE_CODE VARCHAR2(10) NOT NULL,
		LECO_PROVINCE_CODE VARCHAR2(10)
	);

CREATE TABLE METER_HEADER_0123 (
		BATCH_ID VARCHAR2(20) NOT NULL,
		ACCURACY_CLASS VARCHAR2(20),
		BATCH_NO VARCHAR2(20),
		CURRENT_RATING3 NUMBER(19 , 2),
		INITIATED_BY VARCHAR2(20),
		MANUFACTURED_YEAR VARCHAR2(4),
		MANUFACTURER VARCHAR2(50),
		MODEL VARCHAR2(255),
		PROCURED_DATE DATE,
		QUANTITY NUMBER(19 , 2),
		REMARK VARCHAR2(255),
		STATUS VARCHAR2(5),
		UPDATED_USER VARCHAR2(20),
		MANUFACT_ID NUMBER(22 , 1),
		MODEL_ID NUMBER(22 , 1),
		UPDATED_TIME TIMESTAMP(11) DEFAULT sysdate,
		CURRENT_RATING VARCHAR2(20)
	);

CREATE TABLE MANUFACTURER (
		MANUFACT_ID NUMBER(22 , 0) NOT NULL,
		MANUFACT_NAME VARCHAR2(150),
		REMARK VARCHAR2(500),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15),
		CREATED_DATE DATE DEFAULT SYSDATE ,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE TABLE PROVINCE (
		PROVINCE_CODE VARCHAR2(10) NOT NULL,
		LICENSE_CODE VARCHAR2(20) NOT NULL,
		PROVINCE_NAME VARCHAR2(100) NOT NULL,
		DESCRIPTION VARCHAR2(250),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE TABLE DISTRIBUTION_LICENSE (
		LICENSE_CODE VARCHAR2(4) NOT NULL,
		LICENSE_NAME VARCHAR2(100) NOT NULL,
		STATUS NUMBER(2 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE,
		TARIFF_CODE NUMBER(2 , 0) NOT NULL,
		MITFIN_CODE VARCHAR2(20)
	);

CREATE TABLE HTE_SAUSERM (
		ACESS_AUTH NUMBER(2 , 0),
		CHANGE_DT DATE,
		CHANGE_FRQ NUMBER(3 , 0),
		CONF_DT DATE,
		ENT_DT DATE,
		EXPIRY_DT DATE,
		EXP_STATUS VARCHAR2(1),
		LOGIN_PRD NUMBER(1 , 0),
		LOG_ID NUMBER(6 , 0),
		LOG_STATUS VARCHAR2(1),
		MODI_DT DATE,
		TRXN_AUTH NUMBER(1 , 0),
		VALID_PRD NUMBER(3 , 0),
		WARN_PRD NUMBER(3 , 0),
		RN_ NUMBER(10 , 0) NOT NULL,
		STATUS NUMBER(1 , 0),
		USER_LEVEL VARCHAR2(10),
		CONF_BY VARCHAR2(12),
		ENT_BY VARCHAR2(12),
		MODI_BY VARCHAR2(12),
		RPT_USER VARCHAR2(12),
		USER_ID VARCHAR2(12),
		JOB_TITLE VARCHAR2(60),
		PSWRD_HINT VARCHAR2(60),
		USER_NM VARCHAR2(60),
		OLD_PSWRD VARCHAR2(80),
		PSWRD VARCHAR2(80)
	);

CREATE TABLE FEEDER (
		FEEDER_ID NUMBER(22 , 0) NOT NULL,
		SUBSTATION_ID NUMBER(22 , 0) NOT NULL,
		SERIAL_NO VARCHAR2(75) NOT NULL,
		FEEDER_NAME VARCHAR2(100) NOT NULL,
		FEEDER_CODE VARCHAR2(50) NOT NULL,
		DESCRIPTION VARCHAR2(250) NOT NULL,
		NOMINAL_VOLTAGE NUMBER(22 , 0) NOT NULL,
		RATED_VOLTAGE NUMBER(22 , 0),
		RATED_FREQUENCY NUMBER(22 , 0),
		LOCATION_ID VARCHAR2(50) NOT NULL,
		LOCATION_NAME VARCHAR2(100) NOT NULL,
		LATITUDE NUMBER(12 , 9),
		LONGITUDE NUMBER(12 , 9),
		IS_BILLED NUMBER(22 , 0) NOT NULL,
		IS_ACTIVE NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE TABLE METER_HEADER (
		BATCH_ID VARCHAR2(20),
		ACCURACY_CLASS VARCHAR2(20),
		BATCH_NO VARCHAR2(20),
		CURRENT_RATING3 NUMBER(19 , 2),
		INITIATED_BY VARCHAR2(20),
		MANUFACTURED_YEAR VARCHAR2(4),
		PROCURED_DATE DATE,
		QUANTITY NUMBER(19 , 2),
		REMARK VARCHAR2(255),
		STATUS VARCHAR2(5),
		UPDATED_BY VARCHAR2(15),
		MANUFACT_ID NUMBER(22 , 1),
		MODEL_ID NUMBER(22 , 1),
		UPDATED_DATE DATE DEFAULT sysdate,
		CURRENT_RATING VARCHAR2(20),
		CREATED_BY VARCHAR2(15),
		CREATED_DATE DATE
	);

CREATE TABLE FILE_UPLOAD (
		BILL_CYCLE_NO NUMBER(22 , 0) NOT NULL,
		CEB_SERIAL_NO VARCHAR2(20) NOT NULL,
		SERIAL_NO VARCHAR2(20),
		FILE_NAME VARCHAR2(200),
		IS_UPLOADED NUMBER(22 , 0),
		UPLOADED_BY VARCHAR2(15),
		UPLOADED_DATE DATE,
		FILE_TYPE VARCHAR2(20)
	);

CREATE TABLE BILL_CYCLE (
		BILL_CYCLE_NO NUMBER(22 , 0) NOT NULL,
		BILL_YEAR NUMBER(22 , 0),
		BILL_MONTH NUMBER(22 , 0),
		REMARKS VARCHAR2(20),
		IS_UPLOAD_LOCKED NUMBER(22 , 0),
		CREATED_BY VARCHAR2(15),
		CREATED_DATE DATE,
		UPDATED_BY DATE,
		UPDATED_DATE VARCHAR2(20),
		IS_CURRENT NUMBER(22 , 0)
	);

CREATE TABLE PRIMARY_SUBSTATION (
		PSS_ID NUMBER(22 , 0) NOT NULL,
		LICENSE_CODE VARCHAR2(4) NOT NULL,
		PROVINCE_CODE VARCHAR2(10) NOT NULL,
		AREA_CODE VARCHAR2(10) NOT NULL,
		PSS_CODE VARCHAR2(10),
		PSS_NAME VARCHAR2(150) NOT NULL,
		LATITUDE NUMBER(12 , 9),
		LONGITUDE NUMBER(12 , 9),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE DEFAULT sysdate  NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE,
		PSS_CODE_1 VARCHAR2(20)
	);

CREATE TABLE METER_READING (
		BILL_CYCLE_NO NUMBER(22 , 0),
		READING_ID NUMBER(22 , 0) NOT NULL,
		CEB_SERIAL_NO VARCHAR2(20),
		MEASURE_ID NUMBER(22 , 0),
		CURRENT_READING NUMBER(12 , 2),
		CREATED_BY VARCHAR2(15),
		CREATED_DATE DATE,
		UPDATED_BY VARCHAR2(10),
		UPDATED_DATE DATE,
		READING_METHOD VARCHAR2(5),
		PREVIOUS_READING NUMBER(12 , 2),
		ENERGY NUMBER(12 , 2),
		SERIAL_NO VARCHAR2(20)
	);

CREATE TABLE METER_MODEL (
		MODEL_ID NUMBER(22 , 0) NOT NULL,
		MODEL_NAME VARCHAR2(50) NOT NULL,
		MANUFACT_ID NUMBER(22 , 0) NOT NULL,
		REMARK VARCHAR2(500),
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE DEFAULT SYSDATE  NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE TABLE METER_POINT_TEMP (
		SERIAL_NO VARCHAR2(20) NOT NULL,
		METER_POINT_TYPE VARCHAR2(20),
		METER_POINT_NAME VARCHAR2(30),
		NOMINAL_VOLTAGE VARCHAR2(20),
		LICENSE VARCHAR2(20),
		PSS VARCHAR2(25),
		METER_MODEL VARCHAR2(20)
	);

CREATE TABLE TRANSFORMER (
		TRANSORMER_ID NUMBER(22 , 0) NOT NULL,
		SUBSTATION_ID NUMBER(22 , 0) NOT NULL,
		SERIAL_NO VARCHAR2(75) NOT NULL,
		TRANSORMER_NAME VARCHAR2(100) NOT NULL,
		TANSFORMER_CODE VARCHAR2(50) NOT NULL,
		DESCRIPTION VARCHAR2(250) NOT NULL,
		NOMINAL_VOLTAGE NUMBER(22 , 0) NOT NULL,
		RATED_VOLTAGE NUMBER(22 , 0),
		RATED_FREQUENCY NUMBER(22 , 0),
		LOCATION_ID VARCHAR2(50) NOT NULL,
		LOCATION_NAME VARCHAR2(100) NOT NULL,
		LATITUDE NUMBER(12 , 9),
		LONGITUDE NUMBER(12 , 9),
		IS_BILLED NUMBER(22 , 0) NOT NULL,
		STATUS NUMBER(22 , 0) NOT NULL,
		CREATED_BY VARCHAR2(15) NOT NULL,
		CREATED_DATE DATE NOT NULL,
		UPDATED_BY VARCHAR2(15),
		UPDATED_DATE DATE
	);

CREATE UNIQUE INDEX PK_MST_TRANSFORMER ON TRANSFORMER (TRANSORMER_ID ASC);

CREATE UNIQUE INDEX BILL_CYCLE_PK ON BILL_CYCLE (BILL_CYCLE_NO ASC);

CREATE UNIQUE INDEX SYS_C00356230 ON HTE_SAUSERM (RN_ ASC);

CREATE UNIQUE INDEX MEASURE_CELL_PK ON MEASURE_CELL (MODEL_ID ASC, MEASURE_ID ASC);

CREATE UNIQUE INDEX SYS_C00206165 ON METER (CEB_SERIAL_NO ASC);

CREATE UNIQUE INDEX SYS_C00206149 ON METER_HEADER_0123 (BATCH_ID ASC);

CREATE UNIQUE INDEX UI_FEEDER_CODE ON FEEDER (FEEDER_CODE ASC);

CREATE UNIQUE INDEX PK_MST_MANUFACTURER ON MANUFACTURER (MANUFACT_ID ASC);

CREATE UNIQUE INDEX MEASURES_PK ON MEASURE (MEASURE_ID ASC);

CREATE UNIQUE INDEX PK_MST_GRID_SUBSTATION ON GRID_SUBSTATION (GSS_ID ASC);

CREATE UNIQUE INDEX METER_READING_PK ON METER_READING (READING_ID ASC);

CREATE UNIQUE INDEX METER_POINT_UK1 ON METER_POINT (METER_POINT_CODE ASC);

CREATE UNIQUE INDEX METER_READING_UK1 ON METER_READING (BILL_CYCLE_NO ASC, CEB_SERIAL_NO ASC, MEASURE_ID ASC);

CREATE UNIQUE INDEX PK_MST_METER_POINT ON METER_POINT (POINT_ID ASC);

CREATE UNIQUE INDEX PRIMARY_SUBSTATION_UK1 ON PRIMARY_SUBSTATION (PSS_CODE ASC);

CREATE UNIQUE INDEX PK_MST_AREA ON AREA (AREA_CODE ASC);

CREATE UNIQUE INDEX UI_SUBSTATION_CODE ON GRID_SUBSTATION (GSS_CODE ASC);

CREATE UNIQUE INDEX FILE_UPLOAD_PK ON FILE_UPLOAD (BILL_CYCLE_NO ASC, CEB_SERIAL_NO ASC);

CREATE UNIQUE INDEX PK_MST_DISTRIBUTION_LICENSE ON DISTRIBUTION_LICENSE (LICENSE_CODE ASC);

CREATE UNIQUE INDEX PK_MST_MODEL ON METER_MODEL (MODEL_ID ASC);

CREATE UNIQUE INDEX PK_MST_FEEDER ON FEEDER (FEEDER_ID ASC);

CREATE UNIQUE INDEX UI_TANSFORMER_CODE ON TRANSFORMER (TANSFORMER_CODE ASC);

CREATE UNIQUE INDEX PK_MST_PRIMARY_SUBSTATION ON PRIMARY_SUBSTATION (PSS_ID ASC);

CREATE UNIQUE INDEX METER_POINT_TEMP_PK ON METER_POINT_TEMP (SERIAL_NO ASC);

CREATE UNIQUE INDEX METER_POINT_TYPE_PK ON METER_POINT_TYPE (POINT_TYPE_ID ASC);

CREATE UNIQUE INDEX PK_MST_PROVINCE ON PROVINCE (PROVINCE_CODE ASC);

ALTER TABLE AREA ADD CONSTRAINT PK_MST_AREA PRIMARY KEY (AREA_CODE);

ALTER TABLE METER_POINT ADD CONSTRAINT PK_MST_METER_POINT PRIMARY KEY (POINT_ID);

ALTER TABLE GRID_SUBSTATION ADD CONSTRAINT PK_MST_GRID_SUBSTATION PRIMARY KEY (GSS_ID);

ALTER TABLE PRIMARY_SUBSTATION ADD CONSTRAINT PK_MST_PRIMARY_SUBSTATION PRIMARY KEY (PSS_ID);

ALTER TABLE METER_READING ADD CONSTRAINT METER_READING_PK PRIMARY KEY (READING_ID);

ALTER TABLE FEEDER ADD CONSTRAINT PK_MST_FEEDER PRIMARY KEY (FEEDER_ID);

ALTER TABLE METER_HEADER_0123 ADD CONSTRAINT SYS_C00354912 PRIMARY KEY (BATCH_ID);

ALTER TABLE HTE_SAUSERM ADD CONSTRAINT SYS_C00356230 PRIMARY KEY (RN_);

ALTER TABLE MEASURE ADD CONSTRAINT MEASURES_PK PRIMARY KEY (MEASURE_ID);

ALTER TABLE MANUFACTURER ADD CONSTRAINT PK_MST_MANUFACTURER PRIMARY KEY (MANUFACT_ID);

ALTER TABLE BILL_CYCLE ADD CONSTRAINT BILL_CYCLE_PK PRIMARY KEY (BILL_CYCLE_NO);

ALTER TABLE METER_POINT_TEMP ADD CONSTRAINT METER_POINT_TEMP_PK PRIMARY KEY (SERIAL_NO);

ALTER TABLE METER ADD CONSTRAINT SYS_C00354916 PRIMARY KEY (CEB_SERIAL_NO);

ALTER TABLE TRANSFORMER ADD CONSTRAINT PK_MST_TRANSFORMER PRIMARY KEY (TRANSORMER_ID);

ALTER TABLE DISTRIBUTION_LICENSE ADD CONSTRAINT PK_MST_DISTRIBUTION_LICENSE PRIMARY KEY (LICENSE_CODE);

ALTER TABLE METER_MODEL ADD CONSTRAINT PK_MST_MODEL PRIMARY KEY (MODEL_ID);

ALTER TABLE METER_POINT_TYPE ADD CONSTRAINT METER_POINT_TYPE_PK PRIMARY KEY (POINT_TYPE_ID);

ALTER TABLE MEASURE_CELL ADD CONSTRAINT MEASURE_CELL_PK PRIMARY KEY (MODEL_ID, MEASURE_ID);

ALTER TABLE FILE_UPLOAD ADD CONSTRAINT FILE_UPLOAD_PK PRIMARY KEY (BILL_CYCLE_NO, CEB_SERIAL_NO);

ALTER TABLE PROVINCE ADD CONSTRAINT PK_MST_PROVINCE PRIMARY KEY (PROVINCE_CODE);

ALTER TABLE METER_READING ADD CONSTRAINT METER_READING_BILL_CYCLE_FK1 FOREIGN KEY (BILL_CYCLE_NO)
	REFERENCES BILL_CYCLE (BILL_CYCLE_NO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_PROVINCE_FK1 FOREIGN KEY (CEB_PROVINCE_CODE)
	REFERENCES PROVINCE (PROVINCE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PRIMARY_SUBSTATION ADD CONSTRAINT PRIMARY_SUBSTATION_DISTRI_FK1 FOREIGN KEY (LICENSE_CODE)
	REFERENCES DISTRIBUTION_LICENSE (LICENSE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE AREA ADD CONSTRAINT MST_AREA_MST_PROVINCE_FK1 FOREIGN KEY (PROVINCE_CODE)
	REFERENCES PROVINCE (PROVINCE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_METER_POINT_T_FK1 FOREIGN KEY (POINT_TYPE_ID)
	REFERENCES METER_POINT_TYPE (POINT_TYPE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PROVINCE ADD CONSTRAINT PROVINCE_DISTRIBUTION_LIC_FK1 FOREIGN KEY (LICENSE_CODE)
	REFERENCES DISTRIBUTION_LICENSE (LICENSE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_HEADER_0123 ADD CONSTRAINT METER_HEADER_MANUFACTURER_FK1 FOREIGN KEY (MANUFACT_ID)
	REFERENCES MANUFACTURER (MANUFACT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PRIMARY_SUBSTATION ADD CONSTRAINT PRIMARY_SUBSTATION_PROVIN_FK1 FOREIGN KEY (PROVINCE_CODE)
	REFERENCES PROVINCE (PROVINCE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_READING ADD CONSTRAINT METER_READING_MEASURE_FK1 FOREIGN KEY (MEASURE_ID)
	REFERENCES MEASURE (MEASURE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MEASURE_CELL ADD CONSTRAINT MEASURE_CELL_MEASURE_FK1 FOREIGN KEY (MEASURE_ID)
	REFERENCES MEASURE (MEASURE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_PRIMARY_SUBST_FK1 FOREIGN KEY (PSS_ID)
	REFERENCES PRIMARY_SUBSTATION (PSS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE AREA ADD CONSTRAINT MST_AREA_MST_DISTRIBUTION_FK1 FOREIGN KEY (LICENSE_CODE)
	REFERENCES DISTRIBUTION_LICENSE (LICENSE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_PROVINCE_FK2 FOREIGN KEY (LECO_PROVINCE_CODE)
	REFERENCES PROVINCE (PROVINCE_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_READING ADD CONSTRAINT METER_READING_METER_FK1 FOREIGN KEY (CEB_SERIAL_NO)
	REFERENCES METER (CEB_SERIAL_NO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_HEADER_0123 ADD CONSTRAINT METER_HEADER_MODEL_FK1 FOREIGN KEY (MODEL_ID)
	REFERENCES METER_MODEL (MODEL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_AREA_FK1 FOREIGN KEY (AREA_CODE)
	REFERENCES AREA (AREA_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_POINT ADD CONSTRAINT METER_POINT_GRID_SUBSTATI_FK1 FOREIGN KEY (GSS_ID)
	REFERENCES GRID_SUBSTATION (GSS_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE PRIMARY_SUBSTATION ADD CONSTRAINT PRIMARY_SUBSTATION_AREA_FK1 FOREIGN KEY (AREA_CODE)
	REFERENCES AREA (AREA_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE METER_MODEL ADD CONSTRAINT FK_MODEL_MANUFACTURER FOREIGN KEY (MANUFACT_ID)
	REFERENCES MANUFACTURER (MANUFACT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE MEASURE_CELL ADD CONSTRAINT MEASURE_CELL_METER_MODEL_FK1 FOREIGN KEY (MODEL_ID)
	REFERENCES METER_MODEL (MODEL_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

